/* Auto-generated by genmsg_cpp for file /home/urs/fuerte_workspace/visnav2013_exercise3/msg/State.msg */
#ifndef VISNAV2013_EXERCISE3_MESSAGE_STATE_H
#define VISNAV2013_EXERCISE3_MESSAGE_STATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace visnav2013_exercise3
{
template <class ContainerAllocator>
struct State_ {
  typedef State_<ContainerAllocator> Type;

  State_()
  : header()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , yaw(0.0)
  {
  }

  State_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , vx(0.0)
  , vy(0.0)
  , yaw(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _vx_type;
  float vx;

  typedef float _vy_type;
  float vy;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::visnav2013_exercise3::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visnav2013_exercise3::State_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct State
typedef  ::visnav2013_exercise3::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::visnav2013_exercise3::State> StatePtr;
typedef boost::shared_ptr< ::visnav2013_exercise3::State const> StateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::visnav2013_exercise3::State_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::visnav2013_exercise3::State_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace visnav2013_exercise3

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::visnav2013_exercise3::State_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::visnav2013_exercise3::State_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::visnav2013_exercise3::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dc1cc68fd23619b287d1f5536f9e303e";
  }

  static const char* value(const  ::visnav2013_exercise3::State_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdc1cc68fd23619b2ULL;
  static const uint64_t static_value2 = 0x87d1f5536f9e303eULL;
};

template<class ContainerAllocator>
struct DataType< ::visnav2013_exercise3::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "visnav2013_exercise3/State";
  }

  static const char* value(const  ::visnav2013_exercise3::State_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::visnav2013_exercise3::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
float32 vx\n\
float32 vy\n\
\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::visnav2013_exercise3::State_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::visnav2013_exercise3::State_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.vx);
    stream.next(m.vy);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct State_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visnav2013_exercise3::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::visnav2013_exercise3::State_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VISNAV2013_EXERCISE3_MESSAGE_STATE_H

